version: '3.4'

services:
  ecommerce.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - ecommerce.api.products
      - ecommerce.api.orders
      - ecommerce.api.customers
      - ecommerce.api.search
    ports:
      - "6005:80"
